server:
  port: 8765

eureka:
  instance:
   hostname: localhost
   
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: gnr-hrchy-microservice
          uri: http://localhost:8000/
          predicates:
            - Path=/hrchy/**
        - id: gnr-user-microservice
          uri: http://localhost:8001/
          predicates:
            - Path=/user/**
